%% title: 10-1.1 Network
%% description: Section 10 - System Environment - Figure 10-1.1 Network
graph LR
  subgraph External Services
    github["GitHub"]
    slack["Slack"]
    pagerduty["Pager Duty"]
    newrelic["New Relic"]
    statuspage["Status Page"]
    codeclimate["Code Climate"]
    travis["Travis CI"]
    cloudability["Cloudability"]
    visualops["VisualOps"]
  end
  subgraph AWS
    api["API Endpoint"]
    apps-elb["Customer ELB"]
    ops-elb["UAA & Concourse ELB"]
    s3["S3"]
    cloudwatch["CloudWatch"]
    advisor["Trusted Advisor"]
    config["Config"]
    cloudtrail["CloudTrail"]
    route53["Route 53"]
    iam["IAM"]
    iam-perms["IAM Permissions"]
    iam-roles["IAM Roles"]
    aws-console["AWS Console"]
    subgraph cloud.gov Authorization Boundary
      subgraph Production VPC
        prod-az-1a["Availability Zone us-gov-west-1a"]
        prod-az-1b["Availability Zone us-gov-west-1b"]
        vpc-router-prod["VPC Router"]
      end
      vpc-peering["VPC Peering Connection"]
      subgraph Tooling VPC
        tooling-az-1a["Availability Zone us-gov-west-1a"]
        tooling-az-1b["Availability Zone us-gov-west-1b"]
        vpc-router-tooling["VPC Router"]
      end
    end
  end
  customer(("Customer"))
  ops(("Cloud Operations"))

  customer-.DNS.->route53
  customer--Web or CLI-->apps-elb
  customer-->statuspage

  ops-->ops-elb
  ops-->github
  ops-->slack
  ops---aws-console
  ops-->newrelic
  ops-->statuspage
  ops-->pagerduty

  codeclimate-- Static analysis --- github
  travis-- Continuous Testing --- github
  api--Monitoring-->newrelic
  api--Alerting-->pagerduty
  api--API Read-only for infrastructure visualization-->visualops
  api--API Read-only for cost and utilization data-->cloudability

  apps-elb-->prod-az-1a
  apps-elb-->prod-az-1b

  ops-elb-->tooling-az-1a
  ops-elb-->tooling-az-1b

  vpc-router-tooling-->vpc-peering
  vpc-router-prod-->vpc-peering
  aws-console-."Authentication/Authorization".->iam
  iam-.->iam-perms
  iam-perms-.->iam-roles
