%% title: 10-1.2 Production Availability Zone
%% description: Section 10 - System Environment - 10-1.2 Production Availability Zone
graph LR
  subgraph Availability Zone
    subgraph Public Subnet
      nat["NAT Gateway"]
      elb-endpoint>"ELB Endpoint"]
    end
    subgraph Private Subnet - Core Tier A
      cf{"CloudFoundry<br>Core Components"}
    end
    subgraph Private Subnet - Core Tier B
      diego{"CloundFoundry<br>Container Management"}
    end
    subgraph Private Subnet - Database Tier
      rds{"RDS instances"}
    end
    subgraph Private Subnet - Services Tier
      services{"Service instances"}
    end
  end
  apps-elb["Customer ELB"]

  apps-elb---elb-endpoint

  nat---elb-endpoint
  cf---nat
  diego---nat
  rds---nat
  services---nat
