%% title: 10-1.3 Tooling Availability Zone
%% description: Section 10 - System Environment - 0-1.3 Tooling Availability Zone
graph LR
  subgraph Availability Zone
    subgraph Public Subnet
      nat["NAT Gateway"]
      elb-endpoint>"ELB Endpoint"]
    end
    subgraph Private Subnet - Operations Tier
      ops["BOSH Director/UAA"]
    end
    subgraph Private Subnet - Database Tier
      rds{"RDS instances"}
    end
    subgraph Private Subnet - Concourse Tier
      concourse["Concourse - production"]
    end
  end
  ops-elb["UAA & Concourse ELB"]

  ops-elb---elb-endpoint

  nat---elb-endpoint
  ops---nat
  rds---nat
  concourse---nat
