%% title: 10-4.5 Production VPC
%% description: TODO
graph LR
  subgraph Availability Zone us-gov-west-1a
    subgraph Public Subnet
      prod-nat-1a["NAT Gateway"]
      prod-elb-endpoint-1a>"ELB Endpoint"]
    end
    subgraph Private Subnet - Core Tier A
      prod-cf-1a{"CloudFoundry<br>Core Components"}
    end
    subgraph Private Subnet - Core Tier B
      prod-diego-1a{"CloundFoundry<br>Container Management"}
    end
    subgraph Private Subnet - Database Tier
      prod-rds-1a{"RDS instances"}
    end
    subgraph Private Subnet - Services Tier
      prod-services-1a{"Service instances"}
    end
  end
  subgraph Availability Zone us-gov-west-1b
    subgraph Public Subnet
      prod-nat-1b["NAT Gateway"]
      prod-elb-endpoint-1b>"ELB Endpoint"]
    end
    subgraph Private Subnet - Core Tier A
      prod-cf-1b{"CloudFoundry<br>Core Components"}
    end
    subgraph Private Subnet - Core Tier B
      prod-diego-1b{"CloundFoundry<br>Container Management"}
    end
    subgraph Private Subnet - Database Tier
      prod-rds-1b{"RDS instances"}
    end
    subgraph Private Subnet - Services Tier
      prod-services-1b{"Service instances"}
    end
  end
  apps-elb["Customer ELB"]
  vpc-router-prod["VPC Router"]

  apps-elb-->prod-elb-endpoint-1a
  apps-elb-->prod-elb-endpoint-1b

  prod-nat-1a-->prod-elb-endpoint-1a
  prod-nat-1b-->prod-elb-endpoint-1b
  prod-cf-1a-->prod-nat-1a
  prod-cf-1b-->prod-nat-1b
  prod-diego-1a-->prod-nat-1a
  prod-diego-1b-->prod-nat-1b
  prod-rds-1a-->prod-nat-1a
  prod-rds-1b-->prod-nat-1b
  prod-services-1a-->prod-nat-1a
  prod-services-1b-->prod-nat-1b
