%% title: 10-4.6 Tooling VPC
%% description: TODO
graph LR
  subgraph Availability Zone us-gov-west-1a
    subgraph Public Subnet
      tooling-nat-1a["NAT Gateway"]
      tooling-elb-endpoint-1a>"ELB Endpoint"]
    end
    subgraph Private Subnet - Operations Tier
      tooling-ops-1a["BOSH Director/UAA"]
    end
    subgraph Private Subnet - Database Tier
      tooling-rds-1a{"RDS instances"}
    end
    subgraph Private Subnet - Concourse Tier
      tooling-concourse-1a["Concourse - production"]
    end
  end
  subgraph Availability Zone us-gov-west-1b
    subgraph Public Subnet
      tooling-nat-1b["NAT Gateway"]
      tooling-elb-endpoint-1b>"ELB Endpoint"]
    end
    subgraph Private Subnet - Operations Tier
      tooling-ops-1b["Nessus"]
    end
    subgraph Private Subnet - Database Tier
      tooling-rds-1b{"RDS instances"}
    end
    subgraph Private Subnet - Concourse Tier
      tooling-concourse-1b["Concourse - standby"]
    end
  end
  ops-elb["UAA & Concourse ELB"]
  vpc-router-tooling["VPC Router"]

  ops-elb-->tooling-elb-endpoint-1a
  ops-elb-->tooling-elb-endpoint-1b

  tooling-nat-1a-->tooling-elb-endpoint-1a
  tooling-nat-1b-->tooling-elb-endpoint-1b
  tooling-ops-1a-->tooling-nat-1a
  tooling-ops-1b-->tooling-nat-1b
  tooling-rds-1a-->tooling-nat-1a
  tooling-rds-1b-->tooling-nat-1b
  tooling-concourse-1a-->tooling-nat-1a
  tooling-concourse-1b-->tooling-nat-1b
