%% title: 10-4.1 Customer Data Flow
%% description: Section 10 - System Environment - Figure 10-4.1 Customer Data Flow
graph LR
  subgraph AWS
    subgraph CloudFoundry Components
      subgraph Container Management
        Cell["Cell"]
        AppContainer{"Customer<br>Application"}
        Dashboard{Dashboard<br>dashboard.cloud.gov}
      end
      Router[Router]
      SSHProxy[SSH Proxy]
      UAA["User Authentication/Authorization (UAA)<br>login.cloud.gov"]
      CloudController[Cloud Controller<br>api.cloud.gov]
      ServiceBroker[Service Broker]
      Service["Service<br>e.g. MongoDB"]
      HM[Health Monitor]
      Loggregator[Loggregator]
    end
    subgraph Customer Logs
      Parser[Loggregator Parser]
      Q[Redis Queue]
      Logstash[Logstash]
      ES[ElasticSearch]
      Kibana[Kibana<br>logs.cloud.gov]
    end
    ELB("Elastic Load Balancer (ELB)")
    CloudControllerDB(Cloud Controller<br>RDS DB)
  end
  subgraph Customer Responsibility
    SAML{"Single Sign-on (SSO)<br>providing MFA"}
  end
  Customer((Customer))
  statuspage["Status Page<br>cloudgov.statuspage.io"]


  Router-->Cell
  SSHProxy--SSH using temporary key-->Router
  CloudController-.API Request Sets up temporary SSH key.->SSHProxy
  CloudController--Request for provision-->ServiceBroker
  CloudController--Provision/Scale Application Instances-->Cell
  CloudControllerDB-->CloudController
  ServiceBroker--Provisions-->Service
  Service--Service protocol-->AppContainer
  HM--Monitoring of Assigned Port-->AppContainer
  Cell-.Container.->AppContainer
  AppContainer-->Loggregator
  Cell-.Container.->Dashboard

  Parser-->Loggregator
  Parser-->Q
  Logstash-->Q
  Logstash-->ES
  ES-->Kibana

  Customer--HTTPS-->ELB
  Customer--SSH using temporary key-->ELB
  Customer--HTTPS-->statuspage

  ELB --SSH using temporary key--> SSHProxy
  ELB --Web Requests--> Router
  ELB --API Requests--> CloudController
  ELB --> Kibana

  UAA-.Authentication.->SAML
  CloudController-.Authorization.->UAA
  SSHProxy-.Authorization.->UAA
  Kibana-.Authorization.->UAA
