@startuml
'!include https://raw.githubusercontent.com/cloud-gov/cg-diagrams/puml/source/diagrams/ssp.puml
!include ssp.puml

hide stereotype
legend right
| <color:$LEGEND_TITLE_COLOR>**Legend**</color>                             |
|:------------------------------------------------------------------------- |
| <$EXTERNAL_PERSON_BG_COLOR> external person                               |
| <$INHERITED_BG_COLOR> <color:$LEGEND_TITLE_COLOR>inherited system</color> |
| <$SHARED_BG_COLOR> shared system                                          |
| <$SYSTEM_BG_COLOR> Federalist system                                      |
| <$EXTERNAL_SYSTEM_BG_COLOR> external system                               |
| <color:$TLS_COLOR>encrypted connection</color>                            |
| <color:$UNENCRYPTED_CONNECTION_COLOR>unencrypted connection</color>       |
endlegend

skinparam rectangle<<invisible>> {
    backgroundColor #FFFFFF
    borderColor Transparent
    titleFontColor Red
    stereotypeFontColor Transparent
    shadowing false
    fontColor grey
}

skinparam note {
  BorderColor Green
}

Person(npu, "Nonprivileged User", "A Federalist Customer")

note "Auth: OAuth 2.0 \n via Github MFA" as githubfederalistauth
note  "Auth: Token" as webhook 


Boundary(gsa, "GSA Authorized SaaS") {
  System_Ext(gh, "Github", "Customer Source Control")
}

Boundary(awsgov, "AWS GovCloud") {
  Boundary(cloudgov, "cloud.gov") {
    'This hidden rectangle keeps Auth near to each other while behing in d
    'different boundaries
    rectangle gfaconnect<<invisible>> [ 
      | 
    ]
    rectangle webhookconnect<<invisible>> [ 
      / 
    ]
    System_Inherited(elb, "Load Balancer / Router", "cloud.gov")
    System_Inherited(cc, "Control Plane", "cloud.gov")
    System(core, "Federalist Web", "//[Node JS]//")
    System(builder, "Federalist Builder", "//[Node JS]//")
    System(build, "Federalist Build Container", "//[Docker Image]//")
    Db_Shared(db, "Postgres", "AWS RDS")
    Db_Shared(redis, "Redis", "cloud.gov Redis")
    Db_Shared(s3, "Object Storage", "AWS S3")
  }
  System_Inherited(queue, "Build Queue", "AWS SQS")
}
s3-[hidden]redis
' Main flow
HTTPS(npu, gh, "1. commits code modification")
note on link
  Auth: MFA
end note

HTTPS(gh, elb, "2. sends webhook notification")
note on link
  Auth: Token
end note

HTTP_Variable(elb, core, "3. proxies request")

HTTPS(core, queue, "4. sends build message")
note on link
  Auth: Credentials
end note

HTTPS(builder, queue, "5. requests build message")
note on link
  Auth: Credentials
end note

HTTPS(builder, cc, "6. requests build")
note on link
  Auth: Credentials
end note

cc -> build : **7. restages build container**

HTTPS(build, gh, "8. checks out code")
note on link
  Auth: Credentials
  (if private)
end note

HTTPS(build, s3, "9. sends build results")
note on link
  Auth: Credentials
end note

' Other flows
TCP_Variable(core, db, "reads/writes build metadata & configuration")
note on link
  Auth: Credentials/Network
end note

TCPS_Variable(core, redis, "reads/writes build notifications")
note on link
  Auth: Credentials
end note

' Authentication annotations
npu .. githubfederalistauth
githubfederalistauth .. gfaconnect
gfaconnect .. core

gh .r. webhook
webhook .. webhookconnect
webhookconnect .. core
@enduml