@startuml
!include ssp.puml

hide stereotype

Person(pu, "Privileged User", "A Pages Developer")

Boundary(gsa, "GSA-Authorized SaaS") {
  System_Ext(gh, "Github", "Source Control")
}

Boundary(awsgov, "AWS GovCloud") {
  Boundary(cloudgov_boundary, "cloud.gov"){ 
  System(sq, "SonarQube", "Static Analysis")
  System(circle, "Concourse", "CI")
    Boundary(cloudgov, "cloud.gov Platform") {
      System_Inherited(cg, "Control Plane", "cloud.gov")
      System(core, "Pages Application", "//[Node JS/Nginx]//")
    }
  Db_Shared(ecr, "Container Registry", "AWS ECR")
  }
}

' Main flow
HTTPS(pu, gh, "1. merges Pull Request")
note on link
  Auth: MFA
end note

HTTPS(gh, circle, "2. sends webhook notification")
note on link
  Auth: Token
end note

HTTPS_Tight(circle, sq, "sends analysis results")
note on link
  Auth: Token
end note

HTTPS(circle, cg, "3a. sends source")
note on link
  Auth: Credentials
end note

HTTPS(circle, ecr, "3b. sends image")
note on link
  Auth: Credentials
end note

cg -> core : **4a. builds and deploys application**

HTTPS(cg, ecr, "4b. fetches image")
note on link
  Auth: Credentials
end note
@enduml
