%% title: ClamAV
%% description: ClamAV scans for behaviors and virus definitions on each node
graph LR
  subgraph ClamAV
    subgraph Internal
      subgraph All Servers
        clamav["ClamAV Scanner"]
      end
      riemann2["Riemann Event Processor"]
    end
    subgraph External
      clamav-updates["ClamAV Definitions"]
    end

    clamav--Sends Alerts-->riemann2
    clamav-updates--Security Definition Updates-->clamav
  end
