graph LR;
    client_user["fa:fa-user Client Users"]
    login["fa:fa-server Portal URLS:
    <br />- cloud.gov
    <br />- login.cloud.gov
    <br />- uaa.cloud.gov
    <br />- api.cloud.gov
    <br />- logs.cloud.gov
    "]
    elb["fa:fa-code-fork Elastic Load Balancer"]
    client_user-->login
    login--"Port 443"-->elb
    elb-->cf_router_1["fa:fa-random CF Router"]
    elb-->cf_router_2["fa:fa-random CF Router"]
    subgraph Diego Runner 1
        cf_app_1["fa:fa-cogs CF App 1 Container"]
        cf_app_2["fa:fa-cogs CF App 2 Container"]
        cf_app_3["fa:fa-cogs CF App 3 Container"]
    end

    subgraph Diego Runner 2
        style arbitrary color:#000000;
        cf_app_4["fa:fa-cogs CF App 1 Container"]
        cf_app_5["fa:fa-cogs CF App 2 Container"]
        cf_app_6["fa:fa-cogs CF App 3 Container"]
    end


    cf_router_1-->cf_app_2
    cf_router_1-->cf_app_5
    cf_router_2-->cf_app_2
    cf_router_2-->cf_app_5
 
    B-->D
    C-->D
    
    classDef label fill:#f1f1f1, stroke:#f1f1f1, color:#000000
    class arbitrary label
