graph LR
  subgraph Nessus Scanning
    subgraph Internal
      subgraph Tooling VPC
        nessus["Nessus Manager"]
      end
      subgraph All Servers
        nessus-agent1["Nessus Agent"]
      end
    end
    subgraph External
      nessus-updates["GSA Tenable Updates"]
      email2["Email"]
    end

    nessus-agent1--Sends Scanning Results-->nessus
    nessus--Monitors-->nessus-agent1
    nessus-updates--Security Definition Updates-->nessus
    nessus--Reports-->email2
  end
