@startuml
!include ssp.puml

hide stereotype

Person_Ext(public, "Public Viewer", "A member of the public")

Boundary(awsgov, "AWS GovCloud") {
  Boundary(cloudgov_gc, "cloud.gov Platform") {
    System_Inherited(elb, "Load Balancer / Router", "cloud.gov")
        System(proxy, "Pages Proxy", "//[Nginx]//")
        Db_Shared(s3, "Object Store", "AWS S3")
  }
}
Boundary(awscom, "AWS Commercial") {
  Boundary(cloudgov_ew, "cloud.gov Platform") {
      System_Shared(cdn, "CDN", "AWS Cloudfront")    
  }
}

HTTPS(public, cdn, "1a. views static content")
note on link
  Custom Domains
end note

HTTPS(public, elb, "1b. views static content")
note on link
  Preview Domains
end note


cdn -[#green,thickness=2]>> elb : **2. proxies requests**\n//[https 443 (T)]//
HTTP_Variable(elb, proxy, "3. proxies requests")
HTTPS(proxy, s3, "4. proxies requests")
@enduml
