%% title: Services
%% description: How applications provision services such as Database / Caching, and how they are accessed
graph LR
  subgraph Service Provisioning
    service-user["Cloud Foundry User"]
    broker["Service Broker Instance"]
    provider["Service Provider Instance"]
    service-user--Requests service instance-->broker
    broker--Provisions service instance-->s3
    broker--Provisions service instance-->rds
    broker--Provisions service instance-->provider
    subgraph AWS GovCloud
      s3["Amazon Simple Storage Service (S3)"]
      rds["Amazon Relational Database Service (RDS)"]
    end
  end

  subgraph Service Access
    app["Cloud Foundry Application"]
    service-instance["Service Instance"]
    app--Accesses service data-->service-instance
  end
