@startuml
!include ssp.puml

title Pre-SCR example traffic to cloud.gov apps/services
hide stereotype

skinparam note {
  BorderColor Green
}

Person_Ext(public, "Public Viewer", "A member of the public")
Person(dev, "Tenant Developer", "A cloud.gov Tenant")

Boundary(awsgov, "AWS GovCloud") {
  Boundary(cloudgov, "cloud.gov Platform") {
    System_Inherited(alb_0, "App ALB ", "AWS ALB")
    System_Inherited(alb_1, "Mgmt ALB", "AWS ALB")
    System_Inherited(alb_2, "Auth ALB", "AWS ALB")

    System(cf, "CF Router", "")

    System(login, "Login", "")
    System(dashboard, "Dashboard", "")
    System(app, "Customer App", "")
    }
  }

'App flow
'HTTPS(public, waf_0, "App Request", "hide")
'HTTPS_Tight(waf_0, alb_0, "App Request", "hide")
HTTPS(public, alb_0, "App Request")
HTTPS(alb_0, cf, "App Request")
HTTP(cf, app, "App Request")

'Mgmt flow
'HTTPS(dev, waf_1, "Mgmt Request", "hide")
'HTTPS_Tight(waf_1, alb_1, "Mgmt Request", "hide")
HTTPS(dev, alb_1, "Mgmt Request")
HTTPS(alb_1, cf, "Mgmt Request")
HTTP(cf, dashboard, "Mgmt Request")

'Login fly
HTTPS(dev,alb_1, "Login request")
HTTPS(alb_1, cf,  "Login request")

'HTTPS(dev, waf_2, "Login request", "hide")
'HTTPS_Tight(waf_2, alb_2, "Login request", "hide")
HTTPS(dev, alb_2, "Login request")
HTTPS(alb_2, cf, "Login request")
HTTP(cf, login, "Login request")

'Organize or Hide
hide waf_2
hide alb_2
app .[hidden]r. dashboard
dashboard .[hidden]r. login
alb_1 -[norank,hidden]- cf
hide waf_0
hide waf_1
hide waf_2

@enduml
@startuml
!include ssp.puml

title Post-SCR example traffic to cloud.gov apps/services
hide stereotype

skinparam note {
  BorderColor Green
}

Person_Ext(public, "Public Viewer", "A member of the public")
Person(dev, "Tenant Developer", "A cloud.gov Tenant")

Boundary(awsgov, "AWS GovCloud") {
  Boundary(cloudgov, "cloud.gov Platform") {
    System_Inherited(alb_0, "App ALB __//+WAF//__", "AWS ALB")
    System_Inherited(alb_1, "Mgmt ALB __//+WAF//__", "AWS ALB")
    System_Inherited(alb_2, "Auth ALB + __//+WAF//__", "AWS ALB")

    System(cf, "CF Router", "")

    System(login, "Login", "")
    System(dashboard, "Dashboard", "")
    System(app, "Customer App", "")
    }
  }


HTTPS(public, alb_0, "App Request")
'HTTPS_Tight(waf_0, alb_0, "App Request")
HTTPS(public, alb_0, "App Request", "hide")
HTTPS(alb_0, cf, "App Request")
HTTP(cf, app, "App Request")

cf -[norank,hidden]- dashboard

HTTPS(dev, alb_1, "Mgmt Request")
'HTTPS_Tight(waf_1, alb_1, "Mgmt Request")
'HTTPS(dev, alb_1, "Mgmt Request", "hide")
HTTPS(alb_1, cf, "Mgmt Request")
HTTP(cf, dashboard, "Mgmt Request")

HTTPS(dev, alb_2, "Login request")
'HTTPS_Tight(waf_2, alb_2, "Login request")
'HTTPS(dev, alb_2, "Login request", "hide")
HTTPS(alb_2, cf, "Login request")
HTTP(cf, login, "Login request")

'Organize or Hide
dashboard .[hidden]r. login
app .[hidden]r. dashboard
@enduml
