@startuml
!include https://raw.githubusercontent.com/cloud-gov/cg-diagrams/puml/source/diagrams/ssp.puml

hide stereotype
legend right

skinparam note {
  BorderColor Green
}

Person(npu, "Privileged / Nonprivileged User", "A Pages Admin / Customer")

note "Auth: OAuth 2.0\nvia Github MFA" as githubpagesauth

Boundary(awsgov, "AWS GovCloud") {
  Boundary(cloudgov, "cloud.gov Platform") {
    System_Inherited(elb, "Load Balancer / Router", "cloud.gov")
    System(core, "Pages Web", "//[Node JS]//")
    Db_Shared(db, "Postgres", "AWS RDS")
    Db_Shared(redis, "Redis", "cloud.gov Redis")
  }
}

Boundary(gsa, "GSA Authorized SaaS") {
  System_Ext(newrelic, "New Relic", "Monitoring SaaS")
  System_Ext(dap, "DAP", "Analytics collection")
}

HTTPS(npu, elb, "1. requests content")
HTTP_Variable(elb, core, "2. proxies request")

TCPS_Variable(core, db, "3. reads/writes site metadata & configuration")
note on link
  Auth: Credentials/Network
end note

TCPS_Variable(core, redis, "reads/writes notifications")
note on link
  Auth: Credentials
end note

TCPS(core, newrelic, "reports telemetry")
note on link
  Auth: Token
end note

HTTPS(npu, dap, "reports usage")

' Authentication annotations
npu .. githubpagesauth
githubpagesauth .. core
@enduml
