@startuml public_flow
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
'https://github.com/plantuml-stdlib/C4-PlantUML

title Public Site

AddRelTag("TLS", $textColor="grey", $lineColor="green", $lineStyle=BoldLine())

Person_Ext(public, "Public Viewer", "A member of the public")

Boundary(awsgov, "AWS GovCloud") {
    Boundary(cgp_gc, "cloud.gov Platform") {
      SystemDb(s3, "Object Store", "AWS S3")
    }
}

Boundary(awscom, "AWS Commercial") {
  Boundary(cg, "cloud.gov") {
    Boundary(cgp_ew, "cloud.gov platform") {
      System(cdn, "CDN", "AWS Cloudfront")
      System(elb, "Load Balancer / Router", "cloud.gov")
    }
    Container(proxy, "Pages Proxy", "nginx")    
  }
}

Rel(public, cdn, "1a. views static content", "HTTPS 443 (T)", $tags="TLS")
note on link
  Custom Domains
end note
Rel(cdn, elb, "2. proxies requests", "HTTPS 443 (T)", $tags="TLS")

Rel(public, elb, "1b. views static content", "HTTPS 443 (T)", $tags="TLS")
note on link
  Preview Domains
end note
Rel(elb, proxy, "3. proxies requests", "HTTPS 443 (T)", $tags="TLS")

Rel(proxy, s3, "4. proxies requests", "HTTP 80 (T)")

SHOW_LEGEND()
@enduml